### ISSUE TITLE
Pacman is blury, flashes and has a line in his mouth

### ISSUE THREAD

**Issue by PigcraftDev** [SickGodotDev/PAC-MAN#5]

**Comment by SickGodotDev** [comment]
the blurriness is probably due to the low resolution. might have to change some settings to get that fixed.
as for the flashes, they don't seem to appear unless he's animated, so i don't know about those.
huh?
what line in his mouth?
please elaborate

**Comment by SickGodotDev** [comment]
pacman's not blurry anymore!

**Comment by SickGodotDev** [comment]
what do you mean by "line"

**Comment by SickGodotDev** [comment]
pacman no longer flashes!
