### ISSUE TITLE
Pacman still blury. 

### ISSUE THREAD

**Issue by PigcraftDev** [SickGodotDev/PAC-MAN#6]

**Comment by SickGodotDev** [comment]
i don't know what you mean.
maybe chat to me on discord about it when you get home.

**Comment by SickGodotDev** [comment]
he doesn't look blurry to me?

**Comment by PigcraftDev** [comment]
ok i will call you

**Comment by SickGodotDev** [comment]
afetr school right?
or are you at home or something

**Comment by PigcraftDev** [comment]
SCHOOL IS OVER

**Comment by SickGodotDev** [comment]
oh ok
